[package]
name = "system_monitor"
version = "0.1.0"
edition = "2021"

[dependencies]
sysinfo = "0.29"
systemstat = "0.2"
wmi = "0.13"
serde = { version = "1.0", features = ["derive"] }
rand = "0.8.5"
chrono = "0.4.40"
serde_json = "1.0.140"
